swagger: "2.0"
info:
  description: "This is a sample server."
  version: "1.0.0"
  title: "Swagger API"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: ""
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost"
basePath: "/v1"
tags:
- name: "album"
  description: "Everything about album"

schemes:
- "https"
- "http"

paths:
  /albums:
    get:
      tags:
        - "album"
      summary: "Get albums"
      description: ""
      operationId: "GetAlbums"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      responses:
        "200":
          description: "OK"
    post:
      tags:
        - "album"
      summary: "Get albums"
      description: ""
      operationId: "GetAlbums"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "body"
        in: "body"
        schema:
          $ref: "#/definitions/Album"
      responses:
        "200":
          description: "OK"
  /albums/{id}:
    get:
      tags:
        - "album"
      summary: "Get albums"
      description: ""
      operationId: "GetAlbums"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        type: string
        required: true
        default: 1
      responses:
        "200":
          description: "OK"
  


definitions:
  Album:
    type: "object"
    properties:
      id:
        type: string
        default: "4"
      title:
        type: string
        default: "A"
      artist:
        type: string
        default: "Me"
      price:
        type: number
        default: 49.9